### ISSUE TITLE
Examples with callbacks always timeout

### ISSUE THREAD

**Issue by mietzen** [Jorricks/macos-notifications#3] opened 2022-09-19 07:51 UTC
When a reply is sent:
![Untitled](https://user-images.githubusercontent.com/31704359/190971674-b07d4545-7583-4ac8-9fc1-5da6e969f868.gif)

The Notification still timeout in the example. Is this how it should work? My expectation was that we either get a reply and quit or get no reply and timeout. 

```
macOS 12.6
MacBook Pro (14-inch, 2021) M1 Pro
Python 3.10.6
macos-notifications    0.1.5
pyobjc-core            8.5
pyobjc-framework-Cocoa 8.5
```

**Comment by Jorricks** [comment] 2022-09-25 15:41
Hey @mietzen,

Cool to see you used the library. Unfortunately there is no way to know whether the notification was dismissed or not. Because that is not possible, we don't know whether people replied to the notification with a message or click or a button.
Therefore it is unfortunately the expected behaviour.

**Comment by Jorricks** [comment] 2023-05-25 15:03
Closing this

**Closed as completed by Jorricks** 2023-05-25 15:03 UTC
